Fix dependencies
If `gir1.2-webkit-3.0` is installed (per the readme), the program will crash with the following error:

```
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 23, in <module>
    gi.require_version('WebKit2', '4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 106, in require_version
    (namespace, version))
ValueError: Namespace WebKit2 not available for version 4.0
```

I also separated the deps into different lists since the names are very different between distros.